// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAan6vnxkI7XwECKYVCvUddi3ZnNoPpQn8',
    appId: '1:674271699276:web:bb3306a565a854363fefe9',
    messagingSenderId: '674271699276',
    projectId: 'iotpro-10694',
    authDomain: 'iotpro-10694.firebaseapp.com',
    databaseURL: 'https://iotpro-10694-default-rtdb.firebaseio.com',
    storageBucket: 'iotpro-10694.appspot.com',
    measurementId: 'G-0Z96YR6304',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9qSPgAg481C6kAP19B8qAaIdx74q4FdE',
    appId: '1:674271699276:android:a334da70a4cfcd323fefe9',
    messagingSenderId: '674271699276',
    projectId: 'iotpro-10694',
    databaseURL: 'https://iotpro-10694-default-rtdb.firebaseio.com',
    storageBucket: 'iotpro-10694.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_6z48tOneU3WIuhWwe9zqLw7PfMldKIc',
    appId: '1:674271699276:ios:63354378ae4b82093fefe9',
    messagingSenderId: '674271699276',
    projectId: 'iotpro-10694',
    databaseURL: 'https://iotpro-10694-default-rtdb.firebaseio.com',
    storageBucket: 'iotpro-10694.appspot.com',
    androidClientId: '674271699276-3hn6jpdnv6jpdde6s78jo144tu998q4s.apps.googleusercontent.com',
    iosBundleId: 'com.example.filechat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_6z48tOneU3WIuhWwe9zqLw7PfMldKIc',
    appId: '1:674271699276:ios:63354378ae4b82093fefe9',
    messagingSenderId: '674271699276',
    projectId: 'iotpro-10694',
    databaseURL: 'https://iotpro-10694-default-rtdb.firebaseio.com',
    storageBucket: 'iotpro-10694.appspot.com',
    androidClientId: '674271699276-3hn6jpdnv6jpdde6s78jo144tu998q4s.apps.googleusercontent.com',
    iosBundleId: 'com.example.filechat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAan6vnxkI7XwECKYVCvUddi3ZnNoPpQn8',
    appId: '1:674271699276:web:249953be36f656853fefe9',
    messagingSenderId: '674271699276',
    projectId: 'iotpro-10694',
    authDomain: 'iotpro-10694.firebaseapp.com',
    databaseURL: 'https://iotpro-10694-default-rtdb.firebaseio.com',
    storageBucket: 'iotpro-10694.appspot.com',
    measurementId: 'G-H0BQ0LYYPR',
  );
}
